config/routes.rb
Bloccitall::Application.routes.draw do

  devise_for :users
 resources :posts

 resources :advertisements

 get 'about' => 'welcome#about'

 get 'contact' => 'welcome#contact'

  root to: 'welcome#index'

end

app/models/advertisement.rb
class Advertisement < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/advertisements_controller.rb
class AdvertisementsController < ApplicationController
  
  def index
    @advertisements = Advertisement.all
  end

  def show
    @advertisement = Advertisement.find(params[:id])
  end

  def new
    @advertisement = Advertisement.new
  end 

  def create
    @advertisement = Advertisement.new(params.require(:advertisement).permit(:title, :copy, :price))

    if @advertisement.save
      flash[:notice] = "Your advertisement was saved successfully"
      redirect_to @advertisement
    else
      flash[:error] = "Your advertisement was not saved. Please try again"
      render :new
    end
  end


  def edit
    @advertisement = Advertisement.find(params[:id])
  end


  def update
    @advertisement = Advertisement.find(params[:id])

    if @advertisement.update_attributes(params.require(:advertisement).permit(:title, :copy, :price))
    flash[:notice] = "Your advertisement has been updated"
    redirect_to @advertisement
    else
    flash[:notice] = "There was an error updating your advertisement. Please try again"
    render :edit
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def index
    @posts = Post.all
    @posts << Post.new
     #puts "VALUE OF @posts VARIABLE IN INDEX CONTROLLER: #{@posts.inspect}"
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(params.require(:post).permit(:title, :body))
    if @post.save
      flash[:notice] = "Post was saved"
      redirect_to @post
    else
      flash[:error] = "There was an error saving your post. Please try again"
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(params.require(:post).permit(:title, :body))
      flash[:notice] = "Post was updated"
      redirect_to @post
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :edit
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  

  def index
  end

  def about
  end

  def contact
  end
end

app/helpers/advertisements_helper.rb
module AdvertisementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

def my_name
 @my_name = "Anna"
end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/advertisements/edit.html.erb
<h1> Edit Advertisement</h1>

<div class="row">
  <div class="col-md-8">
    <%= form_for @advertisement do |f| %>
      <div class="form-group">
      <%= f.label  :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "Enter title name" %>
      </div>

      <div class="form-group">
      <%= f.label :copy %>
      <%= f.text_area :copy, class: 'form-control', placeholder: 'Enter Copy' %>
      </div>

      <div class="form-group">
      <%= f.label :price %>
      <%= f.number_field :price, class: 'form-control', placeholder: 'Enter Price' %>
      </div>

      <div class="form-group">
      <%= f.submit "Update", class: 'btn btn-sucess' %>
      </div>
    <% end %> 
  </div>
</div>

app/views/advertisements/index.html.erb
<h1>Advertisements</h1>
<% @advertisements.each do | advertisement| %>
  <h2> <%= link_to advertisement.title, advertisement_path(advertisement) %></h2>
  <p>  <%= advertisement.copy %> </p>
  <p>  <%= advertisement.price %> </p>
<% end %>

app/views/advertisements/new.html.erb
<h1> New Advertisement<h1>

<div class="row">
  <div class="col-md-8">
    <%= form_for @advertisement do |f| %>
    <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter title" %>
    </div>

    <div class="form-group">
    <%= f.label :copy %>
    <%= f.text_area :copy, class: 'form-control', placeholder: 'Enter advertisement'%>
    </div>

    <div class="form-group">
    <%= f.label :price %>
    <%= f.number_field :price, class: 'form-control', placeholder: 'Enter price' %>
    </div>

    <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
    </div>
    <% end %>
  </div>
</div>

app/views/advertisements/show.html.erb
<h1><%= @advertisement.title %></h1>
<p> <%= link_to "Edit", edit_advertisement_path, class: 'btn btn-sucess' %>
<p><%= @advertisement.copy %> </p>
<p> price: <%= @advertisement.price %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bloccitall</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="conatiner">
  <ul> 
    <ul class="nav nav-tabs">
    <li><%= link_to "Welcome", root_path %> </li>
    <li><%= link_to  "About", about_path %> </li>
    <li><%= link_to "Contact", contact_path %> </li>
  </ul>

  <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
  <% elsif flash[:error] %>
    <div class="alert alert-sucess">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:error] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
  <% end %>

<%= yield %>

  </div>

</body>
</html>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<div class="row">
  <div class="col-md-8">
    <p>Guidlines for posts</p>
    <ul>
      <li>Make sure that it rhymes.</li>
      <li>Don't use the letter "A"</li>
      <li>The incessant use of hashtags will get you banned.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @post do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
<div>
  

app/views/posts/index.html.erb
<h1>All Posts</h1>
<% @posts.each do |post| %>
  <div class="media">
    <div class="media-body">
      <h4 class="media-heading">
        
        <%= link_to post.title, post %></p>
      </h4>
    </div>
  </div>
<% end %>

app/views/posts/new.html.erb
<h1>New Post </h1>

<div class="row">
  <div class="col-md-8">
    <p>Guidelines for Posts</p>
    <ul>
      <li>Make sure it Rhymes</li>
      <li>Don't use the letter "A"</li>
      <li>The incessant use of hashtags will get you banned. </li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @post do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      <div>
    <% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<%= link_to "Edit", edit_post_path(@post), class: 'btn btn-success' %>

<p><%= @post.body %></p>

app/views/welcome/about.html.erb
<h1>About Bloccitall</h1>
<p>Created by: <%= @my_name %></p>

app/views/welcome/contact.html.erb
<h1>Contact Us</h1>
<p>Find me in app/views/welcome/contact.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
 <p id="index-title">This is the home page for Bloccit.</p>

  <div class="posts">Post 1 goes here.</div>
 <div class="posts">Post 2 goes here.</div>
 <section>I am the content in a section element.</section>